spring.application.name=Chat-Me

#server.port=8882
#server.servlet.context-path=/order
#spring.datasource.url=jdbc:mysql://localhost:3307/chatme
#spring.datasource.username=root
#spring.datasource.password=siddarth22
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=llama3.2
#
#spring.jpa.hibernate.ddl-auto=update 





server.port=${PORT:8882}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.ai.ollama.base-url=${OLLAMA_URL}
spring.ai.ollama.chat.options.model=llama3.2

spring.jpa.hibernate.ddl-auto=update 


